### ISSUE TITLE
[C++] Chinese characters don't work as identifiers

### ISSUE THREAD

**Issue by nobodxbodon** [JoeStrout/miniscript#117]
Hi,
Here's the error I got:
```
> 问好='hi'
Compiler Error: got Unknown(?) where number, string, or identifier is required [line 1]
```
Thanks.

BTW I got here from Farmtronics mod.

**Comment by Withered-Flower-0422** [comment]
String literals in the code are enclosed by double quotes (").
Try `问好 = "hi"`.
ms里的字符串只用双引号括起来。

**Comment by JoeStrout** [comment]
C# MiniScript already does.  (But be sure to use proper quotation marks.)
![image](https://github.com/JoeStrout/miniscript/assets/263365/17954a0d-2799-4e86-bd5e-e6b49bdfe711)

...so if it's not working in Farmtronics, you should open an issue [there](https://github.com/JoeStrout/Farmtronics/issues).

But I see that the C++ version of MiniScript (e.g. command-line MiniScript) struggles with this identifier too.  So I'll leave this issue open here (with an adjusted title).

**Comment by JoeStrout** [comment]
Hmm, well it's not working for me in command-line MiniScript on MacOS.  So, I'm glad that it's working in some cases, but I'll leave this open until we've pinned down exactly what is going on.

**Comment by nobodxbodon** [comment]
Thank you all for the quick responses. Weird it doesn't work for me in windows powershell even with double quotes.
![屏幕截图 2023-12-11 154350](https://github.com/JoeStrout/miniscript/assets/392497/129fb1cc-4edb-40a8-9267-cac3cedc35f1)

**Comment by Withered-Flower-0422** [comment]
MiniScript seems unable to handle with some unicodes very well.
```
> helloWorld = "你好世界"
> helloWorld.len
6  // should be 4
> for i in helloWorld
>>> print i
>>> end for  // try to print all characters

愫


澜

// there are unprintable characters
```
Another example [here](https://discord.com/channels/646000428441534474/646000664656347136/1209213187283492864).

Python does it well enough:
```
>>> helloWorld = '你好世界'
>>> len(helloWorld)
4
>>> for i in helloWorld:
...     print(i)
...
你
好
世
界
```

**Comment by JoeStrout** [comment]
As for Unicode in strings, that's working fine here on MacOS.

![image](https://github.com/JoeStrout/miniscript/assets/263365/6d1572c5-d15d-47a4-bc02-9b4391caf89b)

I wonder if you're on Windows?  We've already seen that the Windows terminal some users use does not handle Unicode properly; for example, `print char(9824)` should print a spade character, but apparently some Windows users see some random Chinese character instead.

Since the Unicode-handling code in MiniScript is the same on all platforms (and does not rely on OS support), I suspect the problem lies in the terminal, where you're typing this code.  If you make a script file containing the same test, and be sure to save that script file as UTF-8, does it work then?

(Of course it's odd that Python handles the same test OK, presumably using the same terminal — I'm not sure what to make of that.)

**Comment by Withered-Flower-0422** [comment]
I'm on windows and both tests are using the same windows terminal(command-line).

**Comment by MineRobber9000** [comment]
Works in WSL Ubuntu as well:
```
khuxkm@wslubuntu:~/miniscript/build$ cat test.ms
helloWorld = "你好世界"
print helloWorld.len

for i in helloWorld
        print i
end for
khuxkm@wslubuntu:~/miniscript/build$ ./miniscript test.ms
4
你
好
世
界
```

**Comment by MineRobber9000** [comment]
Copying my Ubuntu working script to Windows creates the following:

![image](https://github.com/JoeStrout/miniscript/assets/12676241/b76487d4-3253-427d-8eea-1d34755cd0ce)

Which is... "correct"... but the glyphs are wrong. (Opening the file in notepad confirms that the unicode codepoints are correct.)

**Comment by JoeStrout** [comment]
Yeah, that sure looks like an issue with the terminal program, not MiniScript itself.  Poke around in the settings.  I bet there's somewhere to set what encoding it uses to display stdout.  It should be set to UTF-8 (at least when using MiniScript).

**Comment by Withered-Flower-0422** [comment]
It appears to be terminal's fault. The default encoding method is GBK, and after changing that to UTF-8, problems get solved.
(Though I'm still amazed at how Python handles the same test OK.)

**Comment by Withered-Flower-0422** [comment]
Finally things get clear.

- When the encoding method is GBK, Chinese characters can be identifiers, but they **don't** work well in strings.

- When the encoding method is UTF-8, Chinese characters **don't** work as identifiers, but they work well in strings.

Haha, so ironical.
