### ISSUE TITLE
Is C++20 required in 1.6.2?

### ISSUE THREAD

**Issue by toge** [JoeStrout/miniscript#140]
I'm updating miniscript's [Conan recipe](https://conan.io/center/recipes/miniscript).

I found miniscript/1.6.2 requires C++14.
https://github.com/JoeStrout/miniscript/blob/master/CMakeLists.txt#L105-L107

But I found also some sources use C++20 features.
https://github.com/JoeStrout/miniscript/blob/master/MiniScript-cpp/src/MiniScript/MiniscriptTypes.cpp#L18

Is C++20 required in 1.6.2?

**Comment by JoeStrout** [comment]
That requirement is not intended.  If you want to try tweaking it to work with C++14, a PR will be gratefully appreciated.  Or if that proves too difficult, then we'll upgrade the requirement — but let's discuss that here first.
