### ISSUE TITLE
1<2>1 == 1 ?

### ISSUE THREAD

**Issue by badiku** [JoeStrout/miniscript#166]
```
> 1<2>1
1
> 2>1
1
> 1<2
1
> 1<(2>1)
0
> (1<2)>1
0
```

feature?

**Comment by Withered-Flower-0422** [comment]
Miniscript allows continuous judgment. (Like python)

For `1 < 2 > 1`, it's same as ` 1 < 2 and 2 > 1`.

**Comment by badiku** [comment]
nice feature.

https://softwareengineering.stackexchange.com/questions/316969/why-do-most-mainstream-languages-not-support-x-y-z-syntax-for-3-way-boolea

**Comment by badiku** [comment]
how about this code:
```
> 1<2>1<2>1<2>1
1
> 1<2>1
1
> 2>1<2
1
> (1<2>1)<(2>1<2)>1
0
```

**Comment by Withered-Flower-0422** [comment]
Same.

`1 < 2 > 1 < 2 > 1 < 2 > 1` will be `1 < 2 and 2 > 1 and 1 < 2 and 2 > 1 and 1 < 2 and 2 > 1`, which is `true` (as known as `1`).
As for ` (1 < 2 > 1) < (2 > 1 < 2) > 1`, `1 < 2 > 1` is `1`, `2 > 1 < 2` is `1`, so it's the same as `1 < 1 > 1`, which is `flase` (as known as `0`)

**Comment by badiku** [comment]
```
> (a<b<c)<d
1
> a<(b<c<d)
0
> (a<b)<(c<d)
0
> a<b<c<d
1
>
```
can I use `a<b<c<d` to ensure that `a<b and b<c and c<d` ?

**Comment by Withered-Flower-0422** [comment]
of course

**Comment by JoeStrout** [comment]
All working as intended and documented.

**Comment by JoeStrout** [comment]
...and @badiku, please do not use GitHub Issues to discuss things you don't understand about MiniScript.  Join the MiniScript Discord server and discuss there, or send email to the support address.  Help us keep GitHub issues clean.  Thank you!

**Comment by badiku** [comment]
terrible attitude.

miniscript has so many undocumented things that new users can find at their first day, and there is no well defined ebnf syntax, not "well documented",

no further bothering anyway

**Comment by JoeStrout** [comment]
Locking conversation as too heated.
