### ISSUE TITLE
line numbers are incorrect after line continuation

### ISSUE THREAD

**Issue by JoeStrout** [JoeStrout/miniscript#18]
It appears that when the new line continuation feature is used, the line number counts that appear in error messages are no longer correct.

**Comment by sebnozzi** [comment]
What is the "line continuation feature"?

**Comment by JoeStrout** [comment]
https://miniscript.org/wiki/Line_continuation

**Comment by JoeStrout** [comment]
This appears to be working correctly in the current version of Mini Micro.  Test code:
```
print "This is line 1."
x = 1 +
  2 +
  3 *
  4 - 5
print "This is line 6 (though only the 3rd statement.)"
n = null
print "Now on line 8..."; print n.bomb
```
Output:
```
This is line 1.
This is line 6 (though only the 3rd statement.)
Now on line 8...
Runtime Error: Type Error (while attempting to look up bomb) [line 8
```
