### ISSUE TITLE
compiler error: 'else' skips expected 'break'

### ISSUE THREAD

**Issue by JoeStrout** [JoeStrout/miniscript#2]
There seems to be a parsing issue when `break` appears inside an `if` block before an `else` or `else if` section.  The compiler reports **Compiler Error: 'else' skips expected 'break'**, which doesn't make much sense.  Sample code (tested both in Try-It! and in command-line MiniScript):

```
for x in range(1,10)
    if x > 5 then
        print "A"
        break
    else
        print "B"
    end if
end for
print "Done"
```

**Comment by JoeStrout** [comment]
Also occurs in the C# version (tested with classic Unity demo).

**Comment by JoeStrout** [comment]
[Fixed](https://github.com/JoeStrout/miniscript/commit/1caa4f12958e362803084daaa0c4591aa72b68b7).

**Comment by Vitalis11** [comment]
Still meet this error in Greyhack game...

**Comment by JoeStrout** [comment]
Vitalis11 wrote:

> Still meet this error in Greyhack game...

Then you should ask the Greyhack developer to update his copy of MiniScript.

Best,
- Joe
