### ISSUE TITLE
Wrong double value in double.TryParse

### ISSUE THREAD

**Issue by andreakarasho** [JoeStrout/miniscript#20]
If you run the simple miniscript.exe in REPL and write: 0.1, the console output will show you 1 as value.
This is an inconsistent result due to the cultureinfo.
I fixed it putting: 

```csharp
double.TryParse("0.1", NumberStyles.Any, CultureInfo.InvariantCulture, out double value);
```

**Comment by JoeStrout** [comment]
Great catch!  There are probably other places where the code is not international-savvy.  I'll need to do an audit to catch them all (but this a good start).

**Comment by JoeStrout** [comment]
@andreakarasho, this update fixes all the cases I could find in my tests, but I'd love to hear confirmation that it also fixes it for you.
