### ISSUE TITLE
Hashset > array.indexof

### ISSUE THREAD

**Issue by andreakarasho** [JoeStrout/miniscript#26]
here -> https://github.com/JoeStrout/miniscript/blob/master/MiniScript-cs/MiniscriptKeywords.cs

**Comment by JoeStrout** [comment]
Just to be sure I understand: you're suggesting that replacing array.IndexOf with a HashSet in Keywords.IsKeyword would make compilation noticeably faster?

**Comment by andreakarasho** [comment]
No compilation but runtime search yes

**Comment by JoeStrout** [comment]
IsKeyword isn't used at runtime.
