### ISSUE TITLE
command-line MiniScript fails when lines in input script are too long

### ISSUE THREAD

**Issue by JoeStrout** [JoeStrout/miniscript#30]
If command-line MiniScript is given a path to a script file that contains very long lines (e.g., 2700 characters long), it terminates without generating any output (other than the standard version header).

Sample script file that shows the problem (invoking as `miniscript test.ms`, after renaming this file to test.ms of course):

[test.ms.txt](https://github.com/JoeStrout/miniscript/files/4157201/test.ms.txt)

**Comment by Arcnor** [comment]
This doesn't seem to happen anymore? At least with the attached test file...

**Comment by JoeStrout** [comment]
It still happens for me (on macOS).  What platform are you testing on?  Perhaps it's a Unix/Linux thing?

**Comment by Arcnor** [comment]
I'm actually testing on macOS as well, just after downloading the latest commit.

Just to verify, the output should be the number 256 and the "Nothing blablabla" message, right?

Maybe I'm using the wrong class to run it? Not sure if you have more than one CLI-like thing in there 🙂.

**Comment by JoeStrout** [comment]
Just tested again on MacOS (Command-Line (Unix) v1.21; language v1.6.1 (Jun 30 2023)); still happening here.
