### ISSUE TITLE
Unable to distinguish function and variable when parameters are supplied

### ISSUE THREAD

**Issue by yifungkhong** [JoeStrout/miniscript#35]
for example:
x=5
y=x(42) //x is likely a function, but a variable

**Comment by JoeStrout** [comment]
MiniScript intentionally makes no distinction between computation (invoking a function) and storage (accessing a variable).  This is to enable the author of a class or library to freely change from plain variables to functions as needed, without breaking code that uses it.

However if x _were_ a function that took no parameters, and you tried to invoke it with an argument this way, you could get an error:

```
> x = function()
>>> return 5
>>> end function
> y = x(42)
Runtime Exception: Too Many Arguments
```

So this is inconsistent.  To be consistent, we should really throw an error when you try to invoke a number, string, list, or map as a function, with arguments.

**Comment by yifungkhong** [comment]
that sounds OK,but it causes another problem: 
`x = 5
while true
	y = x(42)
end while
`
memory leaks!!! because the arguments pushing and without popping.
the program finally crashes.

**Comment by JoeStrout** [comment]
Wow!  You're right, that is a more serious problem.  I will fix it — thank you!
