### ISSUE TITLE
Parsing errors in compiler: Missing a matching if-statement

### ISSUE THREAD

**Issue by GorgonRamsay** [JoeStrout/miniscript#37]
**Steps to Reproduce:**
1) Compile the following:
```lua
end if
```

**Actual Results:** Compilation was successful.

**Expected Results:** Compiler error, missing a matching if-statement.

**Additional information:**
* You can compile more than one "end if" statement in conjunction without error.
* The issue was observed in the game GreyHack.

**Comment by JoeStrout** [comment]
This does not occur in the current version of MiniScript (in either C++ or C#).

(I believe GreyHack is running an older version of MiniScript.)
