### ISSUE TITLE
`replace` intrinsic needs better error-checking

### ISSUE THREAD

**Issue by JoeStrout** [JoeStrout/miniscript#40]
This code sends MiniScript into an infinite loop:

`replace("foo", "", "x")`

and this code segfaults (at least in command-line MiniScript):

`replace("", "a", "b")`

Desired behavior: throws an error if the second parameter is empty or null; and when the first parameter (self string) is empty, just returns an empty string.

**Comment by MatejTavel** [comment]
Hi, I am looking for my first open source project to contribute to and this one seems to fit my expectation. Do you mind if I tried helping here?

**Comment by JoeStrout** [comment]
@MatejTavel , I would be delighted!  Please submit a pull request when ready and I'll act on it as quickly as I can.

**Comment by JoeStrout** [comment]
@MatejTavel, I incorporated your PR (thank you!) and took it a bit farther, throwing an exception in the case of an empty `oldval` argument, and making sure the C# version gets the same fix.

**Comment by MatejTavel** [comment]
Thank you, I will remember to check the C# next time. And if it is not a problem for you I would suggest that you can leave your comments in the review and I will fix them.
