### ISSUE TITLE
C++ version segfaults on "".upper, "".lower, etc.

### ISSUE THREAD

**Issue by JoeStrout** [JoeStrout/miniscript#41]
Also happens with function form, e.g. `upper("")` or `lower("")`.

Does not happen in the C# version.

**Comment by JoeStrout** [comment]
@MatejTavel here is an issue similar to #40, though it affects only the C++ version.  Want to take a stab at it?

**Comment by MatejTavel** [comment]
Sure, I am going to take look at it.

**Comment by JoeStrout** [comment]
Oops.  Merged your fix, but failed to close the issue.  (Thank you for the fix by the way!)
