### ISSUE TITLE
Intrinsics unit tests

### ISSUE THREAD

**Issue by MatejTavel** [JoeStrout/miniscript#43]
Is there a reason why Intrinsics don't have unit tests? Or is it only because nobody made them so far? I made some while trying fixes for replace and would add some for all Intrinsics if it's not a problem.

**Comment by JoeStrout** [comment]
Intrinsics are generally easier to test through the integration test suite (see TestSuite.txt).  But even there the testing is a bit spotty — feel free to add more!

**Comment by MatejTavel** [comment]
Is there a way to run it in C++ on Linux?

**Comment by MatejTavel** [comment]
Ok, I didn't notice that, thank you.
