### ISSUE TITLE
Incorrect line numbers after "else" statement

### ISSUE THREAD

**Issue by Andreyul** [JoeStrout/miniscript#45]
Compile:
```
if true then
    a = 0
else
!    a = 1
end if
```

Actual: Compiler Error: got Unknown(!) where number, string, or identifier is required [**line 5**]
Expected: Compiler Error: got Unknown(!) where number, string, or identifier is required [**line 4**]

Workaround:
```
if true then
    a = 0
else; // semicolon
!    a = 1
end if
```

**Comment by JoeStrout** [comment]
I'm afraid I wasn't able to reproduce this one either.  With command-line MiniScript:

```
√ DailyPurge % cat > test.ms                                                                                                                   14:52:35
if true then
    a = 0
else
!    a = 1
end if
√ DailyPurge % miniscript test.ms                                                                                                              14:52:40
MiniScript 
Command-Line (Unix) v1; language v1.5 (Aug 19 2020)
Compiler Error: got Unknown(!) where number, string, or identifier is required [line 4]
```

...and with Mini Micro:

```
]source
if true then
    a = 0
else
    !    a = 1
end if

]run
Compiler Error: got Unknown(!) where number, string, or identifier is required [line 4]
...]
```

**Comment by Andreyul** [comment]
This is reproduced at: https://miniscript.org/tryit/

**Comment by JoeStrout** [comment]
Aha, so it is!  (And #46 too I see.)  The Try-It! page is using a slightly outdated version of Mini Micro, and also has some extra code to make the web interface, so the problem could be there.  That means there's nothing to check in here on GitHub for it, but I'll take a look and see if I can get it patched up over there.

Thank you for reporting these.
