### ISSUE TITLE
Error Undefined Identifier: 'self' is unknown in this context when in map/class

### ISSUE THREAD

**Issue by Patrick-van-Halm** [JoeStrout/miniscript#55]
The following code returns the error: `Runtime Error: Undefined Identifier: 'self' is unknown in this context`

```lua
cmdCalculator = {}
cmdCalculator.one = 1
cmdCalculator.addOneToOne = function()
  return self.one + self.one    <== Error is here
end function

traverseMap = function(map, path, delimiter)
  pathSplitted = path.split(delimiter)
  child = map
  success = true
  for p in pathSplitted
    if child.hasIndex(p) then
      child = child[p]
    else
      success = false
      break
    end if
  end for
  if success then return child
  return null
end function

cmds = {"calculator": cmdCalculator}
traverseMap(cmds, "calculator.addOneToOne", ".")
```

**Comment by JoeStrout** [comment]
This is not a bug.  `self` is only defined when you invoke a method with dot syntax, like `cmdCalculator.addOneToOne`.  `self` Refers to the object to the left of the dot. Here you are instead getting the method via square-brackets indexing, and then invoking it with a simple variable.  No dot operator, and so nothing for `self` to refer to.
