### ISSUE TITLE
C# Not able to get only 1 surrogate pair character without using surrogate pair

### ISSUE THREAD

**Issue by Michtdu** [JoeStrout/miniscript#65]
Since char(codepoint) of values > 2^16 don't work anyways why not remove the
Char.ConvertToUtf32 and replace it with a char cast "char c = (char) codepoint"

I don't know how that would work with miniscript so i didn't wanna make a pull request.

**Comment by JoeStrout** [comment]
Just to be clear, can you give an example of code that doesn't work?  And, do we have reason to think that the cast is better than Char.ConvertToUtf32?

**Comment by Michtdu** [comment]
nvm I tried it on greyscript which, after further inspection has a extra class limiting us to only 2 ^ 16 chars
So surrogate pairs work on miniscript.

Besides tough C# handles surrogate pairs with 2 characters which might confuse people using Miniscript because of it's otherwise simplistic nature

Also the C++ implementation uses UTF-8 only anyways so changing the C# implementation to 16 bit would make them more similar

Using Char.ConvertFromUtf32(Int32) with a code point from U+D800 to U+DFFF throws an error. That is kinda annoying because miniscript doesnt have try/except. If you'd use a char cast the char function would simply return a malformed utf-32 string but that is in my opinion better than an error. 

Anyways I'm sorry I assumed GreyScript didn't mess with the char function. Surrogate pairs work perfectly fine altough i still believe they are worse than a char cast.
