### ISSUE TITLE
feature: add math-assignment operators (`+=`, etc.)

### ISSUE THREAD

**Issue by JoeStrout** [JoeStrout/miniscript#72]
See blog post for details: https://luminaryapps.com/blog/math-assign-ops/index.html

**Comment by JoeStrout** [comment]
Just realized a complication that I overlooked before: how does this relate to accessing outer or global variables?

If `x += 1` is literally just syntactic sugar for `x = x + 1`, then if `x` was a global variable and there was not already some local variable of the same name, `x += 1` would create a new local variable with a value of (global) x plus one.  That seems like a gotcha.

In Python, this same situation would produce an UnboundLocalError.  But then, that's also true for `x = x + 1`; Python finds _any_ assignment within a function, and uses that to decide which variables are local.  This can be confusing ([example](https://pythoncircle.com/post/680/solving-python-error-unboundlocalerror-local-variable-x-referenced-before-assignment/)), but avoids any special behavior for +=.

So we need to decide what MiniScript does, which should be whatever is simplest and least surprising.

**Comment by juh9870** [comment]
Imo, the least surprising one would be only operating on locals, and throwing an error if we are accessing outer/globals.
The reasoning for this, is that when writing `x++` one would expect value in variable `x` to get increased by one, hardly anyone expands it to `x=x+1` mentally, and so creating new variable `x` in local scope that is just outer/global x but increased by one is very counterintuitive and will likely cause hard to debug issues

**Comment by JoeStrout** [comment]
Yes, I agree.  So (in detail) the behavior I now intend to implement is:

- if the left-hand side is a simple (unqualified) identifier, then for the rest of the statement, that same unqualified identifier is restricted to lookup in locals _only_.  If it is not found in locals, this will throw a new "Undefined local identifier" error.

So now, `x += 1` will only work if there is already a local variable `x` (from some previous assignment).  If you want to increment a global instead, you just have to be explicit about it: `globals.x += 1` (just as you would with the non-sugared version, `globals.x = globals.x + 1`).

In the future, I could imagine applying this same restriction to ordinary assignments, i.e., `x = x + 1` would only work if a local `x` already exists.  So if you really intend to create a local with a value based on some global, you have to be explicit about it, like `locals.x = x + 1` or `x = globals.x + 1` (or best of all, `locals.x = globals.x + 1`, which makes your intent very clear).  This would avoid a somewhat common bug, and make ordinary assignment consistent with the new math-assign operators.  However that's a potentially code-breaking change, so we'll probably go through a year or two of deprecation before actually throwing an error in this case.

**Comment by juh9870** [comment]
Yes, it's definitely a huge breaking change, but I would highly suggest introducing some keyword for that, like var/let, because writing `locals.` is way too long for something as common as defining a variable

**Comment by JoeStrout** [comment]
Defining a variable isn't precisely what `locals.` does, but it _can_ be used for that, and is an existing feature.  There will be no new keywords.

I also wouldn't describe this as a "huge breaking change" — it is unlikely to affect most code, and where it does have any effect, it's most likely to point out a previously overlooked bug.  The cases where you would write something like `foo = foo+1` and actually _mean_ `locals.foo = globals.foo+1` are extremely rare.  But, a year or two of deprecation will give anyone using such rare cases a reasonable chance to update their code.

**Comment by juh9870** [comment]
Oh, sorry, I misunderstood what you said. Yeah, it's a great feature that would be great to have

**Comment by JoeStrout** [comment]
Implemented with https://github.com/JoeStrout/miniscript/commit/76a73226ecbef5c40f91c6874f6cd00b1b842707, though I will go through and add more integration tests before closing this issue.
