### ISSUE TITLE
`isa null` returns inconsistent results

### ISSUE THREAD

**Issue by JoeStrout** [JoeStrout/miniscript#84]
Sometimes it returns 1 when it should not, but it doesn't do so consistently.  For example:

```miniscript
> 3 isa null
1
> 3 isa number
1
> 3 isa null   
0
>
```

It should always return 1 if the left-hand operand is `null`, and 0 otherwise.

**Comment by juh9870** [comment]
My guess is that `number` is lazily initialized when first used, and so before that prototype of 3 is a null

**Comment by Withered-Flower-0422** [comment]
Not only numbers. List, string, funcRef all share the same problem.
```> string isa null
1
> number isa null
1
> list isa null
1
> funcRef isa null
1
> map isa null
0
> string isa null
0
> number isa null
0
> list isa null
0
> funcRef isa null
0
> {} isa null
0```
