### ISSUE TITLE
Operator precedence issues between unary minus and exponentiation

### ISSUE THREAD

**Issue by JoeStrout** [JoeStrout/miniscript#85]
`-5 ^ 2` should produce 25, but instead produces -25, as if `^` has higher precedence than `-`.

`5 ^ -2` produces a compiler error, again because `-` is not applying to the 2 before `^` is parsed.

Add test cases for this in the integration suite (using both variables and numeric literals), and then fix the compiler to properly give unary minus the highest precedence, even above `^`.

**Comment by juh9870** [comment]
Same should probably apply to other high-priority unary operators, like `new` and `@`

**Comment by JoeStrout** [comment]
Probably the real problem here is `^`, which has a disturbingly high precedence — it should be just above `*` and `/`.

**Comment by juh9870** [comment]
After seeing those implementations in other languages, I think keeping the current `^` order higher than `-` is fine, but the operators `new` and `@` should still be above it.

**Comment by JoeStrout** [comment]
I'm struggling to think of a case where `new` or `@` would appear in an expression with `^`.  Can you give me an example where the current order causes a problem?

**Comment by juh9870** [comment]
`@a ^ @b` where I want to avoid the extra cost of calling variables that I know aren't functions.
