### ISSUE TITLE
Print statements immediately followed by a hyphen/negative symbol fails silently

### ISSUE THREAD

**Issue by chinhouse** [JoeStrout/miniscript#91]
![image](https://github.com/JoeStrout/miniscript/assets/15525424/d9a286d9-82b2-4db9-b80a-fb47dd3a4165)

**Comment by Withered-Flower-0422** [comment]
Actually this is not a bug.
It invokes "print" first and prints an empty line, and returns "null". And "null" minus 10 is still "null", so it won't show anything except an empty line.
